[2023-11-24T14:00:20.708+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:00:17.624455+00:00 [queued]>
[2023-11-24T14:00:20.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:00:17.624455+00:00 [queued]>
[2023-11-24T14:00:20.718+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-24T14:00:20.728+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_and_transform_laod> on 2023-11-24 14:00:17.624455+00:00
[2023-11-24T14:00:20.733+0000] {standard_task_runner.py:57} INFO - Started process 1069 to run task
[2023-11-24T14:00:20.736+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'extract_and_transform_laod', 'manual__2023-11-24T14:00:17.624455+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpkt4ictgj']
[2023-11-24T14:00:20.738+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask extract_and_transform_laod
[2023-11-24T14:00:20.778+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.extract_and_transform_laod manual__2023-11-24T14:00:17.624455+00:00 [running]> on host efa6202eecdb
[2023-11-24T14:00:20.963+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='extract_and_transform_laod' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T14:00:17.624455+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T14:00:17.624455+00:00'
[2023-11-24T14:00:21.170+0000] {logging_mixin.py:151} INFO -   Code tranches         age
0             0   tous ages
1             A     0-4 ans
2             B    5-14 ans
3             C   15-44 ans
4             D   45-64 ans
5             E   65-74 ans
6             F  75 et plus
[2023-11-24T14:00:21.230+0000] {logging_mixin.py:151} INFO -         dep date_de_passage  ...  nbre_hospit_corona_h  nbre_hospit_corona_f
0        01      2022-12-26  ...                   1.0                   3.0
1        01      2022-12-26  ...                   NaN                   NaN
2        01      2022-12-26  ...                   NaN                   NaN
3        01      2022-12-26  ...                   NaN                   NaN
4        01      2022-12-26  ...                   NaN                   NaN
...     ...             ...  ...                   ...                   ...
214215  976      2023-10-24  ...                   NaN                   NaN
214216  976      2023-10-24  ...                   NaN                   NaN
214217  976      2023-10-24  ...                   NaN                   NaN
214218  976      2023-10-24  ...                   NaN                   NaN
214219  976      2023-10-24  ...                   NaN                   NaN

[212928 rows x 12 columns]
[2023-11-24T14:00:21.232+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 45, in extract_and_transform_laod
    df_urgences = df_urgences.merge(df_tranches_dage, left_on='sursaud_cl_age_corona', right_on='Age', how='left')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Age'
[2023-11-24T14:00:21.252+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=extract_and_transform_laod, execution_date=20231124T140017, start_date=20231124T140020, end_date=20231124T140021
[2023-11-24T14:00:21.263+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task extract_and_transform_laod ('Age'; 1069)
[2023-11-24T14:00:21.312+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T14:00:21.326+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
