[2023-11-19T15:47:23.456+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-16T21:56:02.701360+00:00 [queued]>
[2023-11-19T15:47:23.460+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-16T21:56:02.701360+00:00 [queued]>
[2023-11-19T15:47:23.460+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-19T15:47:23.466+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-16 21:56:02.701360+00:00
[2023-11-19T15:47:23.470+0000] {standard_task_runner.py:57} INFO - Started process 23027 to run task
[2023-11-19T15:47:23.473+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'Extract', 'manual__2023-11-16T21:56:02.701360+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmpcz0yhxij']
[2023-11-19T15:47:23.475+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask Extract
[2023-11-19T15:47:23.503+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.Extract manual__2023-11-16T21:56:02.701360+00:00 [running]> on host b6ca478389d2
[2023-11-19T15:47:23.751+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T21:56:02.701360+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-16T21:56:02.701360+00:00'
[2023-11-19T15:47:23.903+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_sample.py:15: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences, delimiter=';', dtype={'Code tranches d\'age': str})

[2023-11-19T15:47:23.951+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sample.py", line 23, in extract_data
    df_departement = pd.read_json('departements-region.json')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File departements-region.json does not exist
[2023-11-19T15:47:23.965+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=Extract, execution_date=20231116T215602, start_date=20231119T154723, end_date=20231119T154723
[2023-11-19T15:47:23.972+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task Extract (File departements-region.json does not exist; 23027)
[2023-11-19T15:47:24.017+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T15:47:24.028+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
