[2023-11-19T19:18:13.970+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:18:10.241297+00:00 [queued]>
[2023-11-19T19:18:13.993+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.Extract manual__2023-11-19T19:18:10.241297+00:00 [queued]>
[2023-11-19T19:18:13.993+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-19T19:18:14.045+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-19 19:18:10.241297+00:00
[2023-11-19T19:18:14.101+0000] {standard_task_runner.py:57} INFO - Started process 967 to run task
[2023-11-19T19:18:14.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'Extract', 'manual__2023-11-19T19:18:10.241297+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_sample.py', '--cfg-path', '/tmp/tmp9b29yeuo']
[2023-11-19T19:18:14.160+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask Extract
[2023-11-19T19:18:14.534+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.Extract manual__2023-11-19T19:18:10.241297+00:00 [running]> on host 4a664210de45
[2023-11-19T19:18:16.388+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T19:18:10.241297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T19:18:10.241297+00:00'
[2023-11-19T19:18:16.679+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_sample.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_sos, delimiter=';', dtype={'Code tranches d\'age': str})

[2023-11-19T19:18:18.080+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sample.py", line 41, in data_transform_and_load
    df_urgences['columns_to_convert'] = df_urgences[columns_to_convert].apply(pd.to_numeric, errors='coerce')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column columns_to_convert
[2023-11-19T19:18:18.329+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=Extract, execution_date=20231119T191810, start_date=20231119T191813, end_date=20231119T191818
[2023-11-19T19:18:18.412+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task Extract (Cannot set a DataFrame with multiple columns to the single column columns_to_convert; 967)
[2023-11-19T19:18:18.593+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:18:18.729+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
