[2023-11-21T20:59:44.633+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:59:25.337863+00:00 [queued]>
[2023-11-21T20:59:44.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:59:25.337863+00:00 [queued]>
[2023-11-21T20:59:44.646+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T20:59:44.662+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_key> on 2023-11-21 20:59:25.337863+00:00
[2023-11-21T20:59:44.668+0000] {standard_task_runner.py:57} INFO - Started process 4548 to run task
[2023-11-21T20:59:44.672+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet_IDD', 'create_key', 'manual__2023-11-21T20:59:25.337863+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpwrainvsi']
[2023-11-21T20:59:44.676+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask create_key
[2023-11-21T20:59:44.728+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet_IDD.create_key manual__2023-11-21T20:59:25.337863+00:00 [running]> on host 726cce66553f
[2023-11-21T20:59:44.963+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_IDD' AIRFLOW_CTX_TASK_ID='create_key' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T20:59:25.337863+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T20:59:25.337863+00:00'
[2023-11-21T20:59:44.965+0000] {sql.py:274} INFO - Executing: ALTER TABLE departements
ADD CONSTRAINT departements_num_dep_key
UNIQUE (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (dep)
REFERENCES departements (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_sursaud_cl_age_corona_fkey
FOREIGN KEY (sursaud_cl_age_corona)
REFERENCES tranches_dage (Code_tranches_dage);
[2023-11-21T20:59:44.973+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-21T20:59:44.981+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-21T20:59:44.994+0000] {sql.py:418} INFO - Running statement: ALTER TABLE departements
ADD CONSTRAINT departements_num_dep_key
UNIQUE (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_dep_fkey
FOREIGN KEY (dep)
REFERENCES departements (num_dep);


ALTER TABLE passages_corona
ADD CONSTRAINT passages_corona_sursaud_cl_age_corona_fkey
FOREIGN KEY (sursaud_cl_age_corona)
REFERENCES tranches_dage (Code_tranches_dage);, parameters: None
[2023-11-21T20:59:45.041+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "code_tranches_dage" referenced in foreign key constraint does not exist

[2023-11-21T20:59:45.050+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet_IDD, task_id=create_key, execution_date=20231121T205925, start_date=20231121T205944, end_date=20231121T205945
[2023-11-21T20:59:45.064+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task create_key (column "code_tranches_dage" referenced in foreign key constraint does not exist
; 4548)
[2023-11-21T20:59:45.086+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T20:59:45.104+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
