[2023-11-21T12:44:15.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet.create_table manual__2023-11-21T12:44:14.553857+00:00 [queued]>
[2023-11-21T12:44:15.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet.create_table manual__2023-11-21T12:44:14.553857+00:00 [queued]>
[2023-11-21T12:44:15.731+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T12:44:15.744+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table> on 2023-11-21 12:44:14.553857+00:00
[2023-11-21T12:44:15.752+0000] {standard_task_runner.py:57} INFO - Started process 745 to run task
[2023-11-21T12:44:15.755+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet', 'create_table', 'manual__2023-11-21T12:44:14.553857+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp9fstgu8o']
[2023-11-21T12:44:15.757+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask create_table
[2023-11-21T12:44:15.801+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet.create_table manual__2023-11-21T12:44:14.553857+00:00 [running]> on host 7789cbe5c52d
[2023-11-21T12:44:16.242+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T12:44:14.553857+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T12:44:14.553857+00:00'
[2023-11-21T12:44:16.244+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS tranches_dage(
      Code_tranches_dage VARCHAR(10),
      Age INT,
      PRIMARY KEY (Code_tranches_dage )
    );

CREATE TABLE IF NOT EXISTS departements (
      num_dep VARCHAR(5),
      dep_name VARCHAR(50),
      region_name VARCHAR(50),
      PRIMARY KEY (num_dep)
   );

CREATE TABLE IF NOT EXISTS passages_corona (
      dep VARCHAR(5),
      date_de_passage DATE,
      sursaud_cl_age_corona INT,
      nbre_pass_corona INT,
      nbre_pass_tot INT,
      nbre_hospit_corona INT,
      nbre_pass_corona_h INT,
      nbre_pass_corona_f INT,
      nbre_pass_tot_h INT,
      nbre_pass_tot_f INT,
      nbre_hospit_corona_h INT,
      nbre_hospit_corona_f INT,
      nbre_acte_corona INT,
      nbre_acte_tot INT,
      nbre_acte_corona_h INT,
      nbre_acte_corona_f INT,
      nbre_acte_tot_h INT,
      nbre_acte_tot_f INT,
    PRIMARY KEY (date_de_passage, sursaud_cl_age_corona)
    );
[2023-11-21T12:44:16.260+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_connexion` isn't defined
[2023-11-21T12:44:16.265+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet, task_id=create_table, execution_date=20231121T124414, start_date=20231121T124415, end_date=20231121T124416
[2023-11-21T12:44:16.279+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task create_table (The conn_id `postgres_connexion` isn't defined; 745)
[2023-11-21T12:44:16.290+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T12:44:16.306+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
